/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeaderLink: typeof import('./src/components/AppHeaderLink.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Textarea: typeof import('primevue/textarea')['default']
    VButton: typeof import('./src/components/ui/button/VButton.vue')['default']
    VCard: typeof import('./src/components/ui/card/VCard.vue')['default']
    VCardContent: typeof import('./src/components/ui/card/VCardContent.vue')['default']
    VCardDescription: typeof import('./src/components/ui/card/VCardDescription.vue')['default']
    VCardFooter: typeof import('./src/components/ui/card/VCardFooter.vue')['default']
    VCardHeader: typeof import('./src/components/ui/card/VCardHeader.vue')['default']
    VCardTitle: typeof import('./src/components/ui/card/VCardTitle.vue')['default']
    VCheckbox: typeof import('./src/components/ui/checkbox/VCheckbox.vue')['default']
    VFormControl: typeof import('./src/components/ui/form/VFormControl.vue')['default']
    VFormDescription: typeof import('./src/components/ui/form/VFormDescription.vue')['default']
    VFormItem: typeof import('./src/components/ui/form/VFormItem.vue')['default']
    VFormLabel: typeof import('./src/components/ui/form/VFormLabel.vue')['default']
    VFormMessage: typeof import('./src/components/ui/form/VFormMessage.vue')['default']
    VInput: typeof import('./src/components/ui/input/VInput.vue')['default']
    VLabel: typeof import('./src/components/ui/label/VLabel.vue')['default']
    VSelect: typeof import('./src/components/ui/select/VSelect.vue')['default']
    VSelectContent: typeof import('./src/components/ui/select/VSelectContent.vue')['default']
    VSelectGroup: typeof import('./src/components/ui/select/VSelectGroup.vue')['default']
    VSelectItem: typeof import('./src/components/ui/select/VSelectItem.vue')['default']
    VSelectItemText: typeof import('./src/components/ui/select/VSelectItemText.vue')['default']
    VSelectLabel: typeof import('./src/components/ui/select/VSelectLabel.vue')['default']
    VSelectScrollDownButton: typeof import('./src/components/ui/select/VSelectScrollDownButton.vue')['default']
    VSelectScrollUpButton: typeof import('./src/components/ui/select/VSelectScrollUpButton.vue')['default']
    VSelectSeparator: typeof import('./src/components/ui/select/VSelectSeparator.vue')['default']
    VSelectTrigger: typeof import('./src/components/ui/select/VSelectTrigger.vue')['default']
    VSelectValue: typeof import('./src/components/ui/select/VSelectValue.vue')['default']
    VTable: typeof import('./src/components/ui/table/VTable.vue')['default']
    VTableBody: typeof import('./src/components/ui/table/VTableBody.vue')['default']
    VTableCaption: typeof import('./src/components/ui/table/VTableCaption.vue')['default']
    VTableCell: typeof import('./src/components/ui/table/VTableCell.vue')['default']
    VTableEmpty: typeof import('./src/components/ui/table/VTableEmpty.vue')['default']
    VTableFooter: typeof import('./src/components/ui/table/VTableFooter.vue')['default']
    VTableHead: typeof import('./src/components/ui/table/VTableHead.vue')['default']
    VTableHeader: typeof import('./src/components/ui/table/VTableHeader.vue')['default']
    VTableRow: typeof import('./src/components/ui/table/VTableRow.vue')['default']
  }
}
