// hash:72bb12c30a7665fe55be82a866bde94e0371cd5b2fbc6b4da885468a10090965
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @cultura-ai/ioc

export {};

declare module '@cultura-ai/ioc' {
	interface IocMap {
		
	}

	function ioc<Key extends keyof IocMap>(id: Key): IocMap[Key];
}
