// hash:e31b2e8aca15a3a29bc6f456da4ed4bd04a861bfc4325ff82661bdd12603da4d
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @cultura-ai/ioc

export {};

declare module '@cultura-ai/ioc' {
	interface IocMap {
		"KeyValue": import('./src/services/KeyValue.service.ts').KeyValueService;
		"Mediasoup": import('./src/services/Mediasoup.service.ts').MediasoupService;
		"WsServer": import('./src/services/WsServer.service.ts').WsServer;
	}

	function ioc<Key extends keyof IocMap>(id: Key): IocMap[Key];
}
